# Generated by Django 5.2.4 on 2025-08-14 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_barcodealias'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwarditem',
            name='barcode_alias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.barcodealias'),
        ),
        migrations.AddField(
            model_name='openingstock',
            name='barcode_alias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.barcodealias'),
        ),
        migrations.AddField(
            model_name='outwarditem',
            name='barcode_alias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.barcodealias'),
        ),
    ]
